"""add stock_masters and stock_candles

Revision ID: 64ea2ba3255f
Revises: f6ea9be370b3
Create Date: 2026-02-26 15:59:36.281730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ea2ba3255f'
down_revision: Union[str, None] = 'f6ea9be370b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_candles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval', sa.String(length=5), server_default='1d', nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'dt', 'interval', name='uq_candle')
    )
    op.create_index('ix_candle_lookup', 'stock_candles', ['symbol', 'interval', 'dt'], unique=False)
    op.create_table('stock_masters',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_masters')
    op.drop_index('ix_candle_lookup', table_name='stock_candles')
    op.drop_table('stock_candles')
    # ### end Alembic commands ###
