"""add optimal_horizon and half_life_days to alpha_factors

Revision ID: df18b79a44ba
Revises: aa0b1c2d3e4f
Create Date: 2026-04-05 18:07:26.165387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df18b79a44ba'
down_revision: Union[str, None] = 'aa0b1c2d3e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bds_run_trade', table_name='backtest_daily_snapshots')
    op.drop_table('backtest_daily_snapshots')
    op.drop_index('ix_telegram_logs_category', table_name='telegram_message_logs')
    op.drop_index('ix_telegram_logs_created', table_name='telegram_message_logs')
    op.drop_table('telegram_message_logs')
    op.drop_index('ix_gen_report_interval_created', table_name='alpha_generation_reports')
    op.drop_index('ix_gen_report_interval_gen', table_name='alpha_generation_reports')
    op.drop_table('alpha_generation_reports')
    op.drop_index('ix_stress_test_runs_status', table_name='stress_test_runs')
    op.drop_table('stress_test_runs')
    op.drop_index('ix_backtest_runs_created_at', table_name='backtest_runs')
    op.drop_index('ix_backtest_runs_status', table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index('ix_alpha_experiences_ic_mean', table_name='alpha_experiences')
    op.drop_index('ix_alpha_experiences_success', table_name='alpha_experiences')
    op.drop_table('alpha_experiences')
    op.drop_index('ix_mcp_audit_logs_created_at', table_name='mcp_audit_logs')
    op.drop_index('ix_mcp_audit_logs_tool_name', table_name='mcp_audit_logs')
    op.drop_table('mcp_audit_logs')
    op.drop_table('alpha_mining_runs')
    op.drop_index('ix_tmr_key_date', table_name='telegram_message_registry')
    op.drop_table('telegram_message_registry')
    op.drop_index('ix_alpha_factors_causal_robust', table_name='alpha_factors')
    op.drop_index('ix_alpha_factors_created_at', table_name='alpha_factors')
    op.drop_index('ix_alpha_factors_expression_hash', table_name='alpha_factors')
    op.drop_index('ix_alpha_factors_fitness_composite', table_name='alpha_factors')
    op.drop_index('ix_alpha_factors_ic_mean', table_name='alpha_factors')
    op.drop_index('ix_alpha_factors_icir', table_name='alpha_factors')
    op.drop_index('ix_alpha_factors_interval', table_name='alpha_factors')
    op.drop_index('ix_alpha_factors_max_drawdown', table_name='alpha_factors')
    op.drop_index('ix_alpha_factors_mining_run_id', table_name='alpha_factors')
    op.drop_index('ix_alpha_factors_population_active', table_name='alpha_factors')
    op.drop_index('ix_alpha_factors_sharpe', table_name='alpha_factors')
    op.drop_index('ix_alpha_factors_status', table_name='alpha_factors')
    op.drop_table('alpha_factors')
    op.drop_index('ix_sim_replay_runs_created_at', table_name='sim_replay_runs')
    op.drop_index('ix_sim_replay_runs_mode', table_name='sim_replay_runs')
    op.drop_index('ix_sim_replay_runs_symbol', table_name='sim_replay_runs')
    op.drop_table('sim_replay_runs')
    op.drop_index('ix_dart_financials_sym_year', table_name='dart_financials')
    op.alter_column('discussion_posts', 'is_spam',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('discussion_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('discussion_sentiment_hourly', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('investor_trading', 'foreign_net',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('investor_trading', 'inst_net',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('investor_trading', 'retail_net',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('investor_trading', 'foreign_buy_vol',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('investor_trading', 'foreign_sell_vol',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('investor_trading', 'inst_buy_vol',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('investor_trading', 'inst_sell_vol',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('investor_trading', 'retail_buy_vol',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('investor_trading', 'retail_sell_vol',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('live_feedback', 'trade_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('live_feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('live_trades', 'executed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('live_trades', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('llm_usage_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('margin_short_daily', 'margin_balance',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('margin_short_daily', 'margin_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('margin_short_daily', 'short_volume',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('margin_short_daily', 'short_balance',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('margin_short_daily', 'short_balance_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('news_articles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_news_articles_symbols_gin', table_name='news_articles', postgresql_using='gin')
    op.alter_column('news_sentiment_daily', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('program_trading', 'pgm_buy_amount',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('program_trading', 'pgm_sell_amount',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('program_trading', 'pgm_net_amount',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('program_trading', 'arbt_buy_amount',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('program_trading', 'arbt_sell_amount',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('program_trading', 'nabt_buy_amount',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('program_trading', 'nabt_sell_amount',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('replay_runs', 'factor_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('replay_runs', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('replay_runs', 'sessions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('replay_runs', 'aggregate_metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('replay_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('stock_ticks_ts_idx', table_name='stock_ticks')
    op.alter_column('trading_contexts', 'initial_capital',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text("'100000000'::numeric"))
    op.alter_column('trading_contexts', 'position_size_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0.1'::double precision"))
    op.alter_column('trading_contexts', 'max_positions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('trading_contexts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trading_contexts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('worker_commands', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('worker_state', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflow_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('workflow_events', 'level')
    op.alter_column('workflow_runs', 'trade_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('workflow_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('uq_wf_date', table_name='workflow_runs')
    op.create_unique_constraint('uq_wf_date', 'workflow_runs', ['date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_wf_date', 'workflow_runs', type_='unique')
    op.create_index('uq_wf_date', 'workflow_runs', ['date'], unique=True)
    op.alter_column('workflow_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflow_runs', 'trade_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('workflow_events', sa.Column('level', sa.VARCHAR(length=10), server_default=sa.text("'info'::character varying"), autoincrement=False, nullable=True))
    op.alter_column('workflow_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('worker_state', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('worker_commands', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trading_contexts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trading_contexts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trading_contexts', 'max_positions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.alter_column('trading_contexts', 'position_size_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0.1'::double precision"))
    op.alter_column('trading_contexts', 'initial_capital',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text("'100000000'::numeric"))
    op.create_index('stock_ticks_ts_idx', 'stock_ticks', [sa.text('ts DESC')], unique=False)
    op.alter_column('replay_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('replay_runs', 'aggregate_metrics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('replay_runs', 'sessions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('replay_runs', 'config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('replay_runs', 'factor_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('program_trading', 'nabt_sell_amount',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('program_trading', 'nabt_buy_amount',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('program_trading', 'arbt_sell_amount',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('program_trading', 'arbt_buy_amount',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('program_trading', 'pgm_net_amount',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('program_trading', 'pgm_sell_amount',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('program_trading', 'pgm_buy_amount',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('news_sentiment_daily', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_news_articles_symbols_gin', 'news_articles', [sa.text('(symbols::jsonb)')], unique=False, postgresql_using='gin')
    op.alter_column('news_articles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('margin_short_daily', 'short_balance_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('margin_short_daily', 'short_balance',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('margin_short_daily', 'short_volume',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('margin_short_daily', 'margin_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('margin_short_daily', 'margin_balance',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('llm_usage_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('live_trades', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('live_trades', 'executed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('live_feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('live_feedback', 'trade_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('investor_trading', 'retail_sell_vol',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('investor_trading', 'retail_buy_vol',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('investor_trading', 'inst_sell_vol',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('investor_trading', 'inst_buy_vol',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('investor_trading', 'foreign_sell_vol',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('investor_trading', 'foreign_buy_vol',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('investor_trading', 'retail_net',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('investor_trading', 'inst_net',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('investor_trading', 'foreign_net',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('discussion_sentiment_hourly', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('discussion_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('discussion_posts', 'is_spam',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index('ix_dart_financials_sym_year', 'dart_financials', ['symbol', 'fiscal_year'], unique=False)
    op.create_table('sim_replay_runs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('interval', sa.VARCHAR(length=10), server_default=sa.text("'5m'::character varying"), autoincrement=False, nullable=False),
    sa.Column('strategy_preset', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('factor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('data_source', sa.VARCHAR(length=20), server_default=sa.text("'synthetic'::character varying"), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('total_bars', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_events', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('pnl', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('pnl_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('events', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('final_state', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('analysis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('mode', sa.VARCHAR(length=20), server_default=sa.text("'single'::character varying"), autoincrement=False, nullable=False),
    sa.Column('universe', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tick_summaries', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('trade_log_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('decisions_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('equity_curve', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('total_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('final_equity', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sim_replay_runs_pkey')
    )
    op.create_index('ix_sim_replay_runs_symbol', 'sim_replay_runs', ['symbol'], unique=False)
    op.create_index('ix_sim_replay_runs_mode', 'sim_replay_runs', ['mode'], unique=False)
    op.create_index('ix_sim_replay_runs_created_at', 'sim_replay_runs', ['created_at'], unique=False)
    op.create_table('alpha_factors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('mining_run_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('expression_str', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expression_sympy', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('polars_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hypothesis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('generation', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('ic_mean', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ic_std', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('icir', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('turnover', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sharpe', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_drawdown', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'''discovered'''::character varying"), autoincrement=False, nullable=False),
    sa.Column('causal_robust', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('causal_effect_size', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('causal_p_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('parent_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('factor_type', sa.VARCHAR(length=20), server_default=sa.text("'''single'''::character varying"), autoincrement=False, nullable=False),
    sa.Column('component_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('fitness_composite', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tree_depth', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tree_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expression_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('operator_origin', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('is_elite', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('population_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('birth_generation', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('interval', sa.VARCHAR(length=5), server_default=sa.text("'1d'::character varying"), autoincrement=False, nullable=False),
    sa.Column('last_evaluated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('live_ic_7d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('live_sharpe_7d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('staleness_warning', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('causal_failure_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('genotypic_age', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mining_run_id'], ['alpha_mining_runs.id'], name='alpha_factors_mining_run_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='alpha_factors_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_alpha_factors_status', 'alpha_factors', ['status'], unique=False)
    op.create_index('ix_alpha_factors_sharpe', 'alpha_factors', ['sharpe'], unique=False)
    op.create_index('ix_alpha_factors_population_active', 'alpha_factors', ['population_active'], unique=False)
    op.create_index('ix_alpha_factors_mining_run_id', 'alpha_factors', ['mining_run_id'], unique=False)
    op.create_index('ix_alpha_factors_max_drawdown', 'alpha_factors', ['max_drawdown'], unique=False)
    op.create_index('ix_alpha_factors_interval', 'alpha_factors', ['interval'], unique=False)
    op.create_index('ix_alpha_factors_icir', 'alpha_factors', ['icir'], unique=False)
    op.create_index('ix_alpha_factors_ic_mean', 'alpha_factors', ['ic_mean'], unique=False)
    op.create_index('ix_alpha_factors_fitness_composite', 'alpha_factors', ['fitness_composite'], unique=False)
    op.create_index('ix_alpha_factors_expression_hash', 'alpha_factors', ['expression_hash'], unique=False)
    op.create_index('ix_alpha_factors_created_at', 'alpha_factors', ['created_at'], unique=False)
    op.create_index('ix_alpha_factors_causal_robust', 'alpha_factors', ['causal_robust'], unique=False)
    op.create_table('telegram_message_registry',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'sent'::character varying"), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('sender', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='telegram_message_registry_pkey'),
    sa.UniqueConstraint('message_key', 'date', name='uq_tmr_key_date')
    )
    op.create_index('ix_tmr_key_date', 'telegram_message_registry', ['message_key', 'date'], unique=False)
    op.create_table('alpha_mining_runs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'''PENDING'''::character varying"), autoincrement=False, nullable=False),
    sa.Column('progress', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('factors_found', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_evaluated', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('iteration_logs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='alpha_mining_runs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('mcp_audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tool_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('input_params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('output', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'''success'''::character varying"), autoincrement=False, nullable=False),
    sa.Column('blocked_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('execution_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='mcp_audit_logs_pkey')
    )
    op.create_index('ix_mcp_audit_logs_tool_name', 'mcp_audit_logs', ['tool_name'], unique=False)
    op.create_index('ix_mcp_audit_logs_created_at', 'mcp_audit_logs', ['created_at'], unique=False)
    op.create_table('alpha_experiences',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('factor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('expression_str', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('hypothesis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ic_mean', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('generation', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('parent_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('failure_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['factor_id'], ['alpha_factors.id'], name='alpha_experiences_factor_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='alpha_experiences_pkey')
    )
    op.create_index('ix_alpha_experiences_success', 'alpha_experiences', ['success'], unique=False)
    op.create_index('ix_alpha_experiences_ic_mean', 'alpha_experiences', ['ic_mean'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('strategy_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('strategy_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('initial_capital', sa.NUMERIC(precision=18, scale=2), server_default=sa.text("'100000000'::numeric"), autoincrement=False, nullable=False),
    sa.Column('cost_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('symbol_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'''PENDING'''::character varying"), autoincrement=False, nullable=False),
    sa.Column('progress', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('equity_curve', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('trades_summary', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='backtest_runs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_backtest_runs_status', 'backtest_runs', ['status'], unique=False)
    op.create_index('ix_backtest_runs_created_at', 'backtest_runs', ['created_at'], unique=False)
    op.create_table('stress_test_runs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('strategy_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('scenario_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('scenario_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('agent_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('exchange_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'''PENDING'''::character varying"), autoincrement=False, nullable=False),
    sa.Column('progress', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_steps', sa.INTEGER(), server_default=sa.text('1000'), autoincrement=False, nullable=False),
    sa.Column('results', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='stress_test_runs_pkey')
    )
    op.create_index('ix_stress_test_runs_status', 'stress_test_runs', ['status'], unique=False)
    op.create_table('alpha_generation_reports',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('generation', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_interval', sa.VARCHAR(length=5), server_default=sa.text("'1d'::character varying"), autoincrement=False, nullable=False),
    sa.Column('cycle_num', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('report_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='alpha_generation_reports_pkey')
    )
    op.create_index('ix_gen_report_interval_gen', 'alpha_generation_reports', ['data_interval', 'generation'], unique=False)
    op.create_index('ix_gen_report_interval_created', 'alpha_generation_reports', ['data_interval', 'created_at'], unique=False)
    op.create_table('telegram_message_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), server_default=sa.text("'''system'''::character varying"), autoincrement=False, nullable=False),
    sa.Column('caller', sa.VARCHAR(length=100), server_default=sa.text("''''''::character varying"), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'''success'''::character varying"), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('telegram_message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='telegram_message_logs_pkey')
    )
    op.create_index('ix_telegram_logs_created', 'telegram_message_logs', ['created_at'], unique=False)
    op.create_index('ix_telegram_logs_category', 'telegram_message_logs', ['category'], unique=False)
    op.create_table('backtest_daily_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('backtest_run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trade_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('snapshot_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], name='backtest_daily_snapshots_backtest_run_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='backtest_daily_snapshots_pkey'),
    sa.UniqueConstraint('backtest_run_id', 'trade_index', 'snapshot_date', name='uq_bds_run_trade_date')
    )
    op.create_index('idx_bds_run_trade', 'backtest_daily_snapshots', ['backtest_run_id', 'trade_index'], unique=False)
    # ### end Alembic commands ###
