"""initial schema

Revision ID: f6ea9be370b3
Revises: 
Create Date: 2026-02-25 23:11:43.337667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ea9be370b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mode', sa.Enum('REAL', 'PAPER', name='account_mode'), nullable=False),
    sa.Column('total_capital', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='order_side'), nullable=False),
    sa.Column('type', sa.Enum('MARKET', 'LIMIT', name='order_type'), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'FILLED', 'PARTIAL', 'CANCELLED', 'REJECTED', name='order_status'), server_default='PENDING', nullable=False),
    sa.Column('mode', sa.Enum('REAL', 'PAPER', name='account_mode'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.Enum('REAL', 'PAPER', name='account_mode'), nullable=False),
    sa.Column('qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_ticks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_ticks_symbol'), 'stock_ticks', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_ticks_symbol'), table_name='stock_ticks')
    op.drop_table('stock_ticks')
    op.drop_table('positions')
    op.drop_table('orders')
    op.drop_table('accounts')
    # ### end Alembic commands ###
